
import Allianzlogo from './page1/Allianzlogo.png';
import getstartedarrow from './page1/getstartedarrow.png';
import Discovermorearrow from './page1/Discovermorearrow.png';
import Facebookicon from './page5/Facebookicon.png';
import Twitericon from './page5/Twitericon.png';
import Instagramicon from './page5/Instagramicon.png';
import Footericon from './page5/footericon.png';
import p2manwalking from './page2/p2manwalking.png';
import portraitcorporatewoman1 from './page2/portraitcorporatewoman1.png';
import phoneimage from './page2/phoneimage.png';
import smiling from './page2/smiling.png';
import contactimage from './page5/contactimage.png';
import Landingpageimage from './page1/Landingpageimage.png';
import image24 from './page1/image24.png';
import Travelconceptwithdocuments from './page1/Travelconceptwithdocuments.png';
import Sectorimage1 from './page4/Sectorimage1.png';
import Sectorimage2 from './page4/Sectorimage2.png';
import Sectorimage3 from './page4/Sectorimage3.png';
import Sectorimage4 from './page4/Sectorimage4.png';
import womanwithlaptop from './page3/womanwithlaptop.png';
import tabimage from './page4/tabimage.png';
import redcross from './page1/redcross.png';
import image888 from './page1/image888.png';
import CIBM from './page1/CIBM.png';
import Nuvei from './page1/Nuvei.png';
import moneygramm from './page1/moneygramm.png';
import Rakbank from './page1/Rakbank.png';
import serviceslovehand from './page4/serviceslovehand.png';
import servicesnetwork from './page4/servicesnetwork.png';
import servicessecurity from './page4/servicessecurity.png';
import servicesexpert from './page4/servicesexpert.png';
import servicesmain from './page4/servicesmain.png';



export{
        Allianzlogo,
        getstartedarrow,
        Discovermorearrow,
        Facebookicon,
        Twitericon,
        Instagramicon,
        Footericon,
        p2manwalking,
        portraitcorporatewoman1,
        phoneimage,
        smiling,
        contactimage,
        Landingpageimage,
        image24,
        Travelconceptwithdocuments,
        Sectorimage1,
        Sectorimage2,
        Sectorimage3,
        Sectorimage4,
        womanwithlaptop,
        tabimage,
        redcross,
        image888,
        CIBM,
        Nuvei,
        moneygramm,
        Rakbank,
        serviceslovehand,
        servicesnetwork,
        servicessecurity,
        servicesexpert,
        servicesmain
}

